### ISSUE TITLE
OS 1주차 : 운영체제의 개요

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#1]
### **목표**
운영 체제의 개요 이해하기.

### **마감 일시 (한국 시간 기준)**
2021년 9월 12일 오후 11시

**Comment by POL6463** [comment]
OS 1주차입니다
https://pol6463.github.io/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C(1%EC%A3%BC%EC%B0%A8)/

**Comment by Gnu-Kenny** [comment]
OS 1주차입니다.
[Chapter1_OS_Summary](https://github.com/Gnu-Kenny/CS-study/tree/main/OS/Chapter1_OS_Summary)

**Comment by JerryK026** [comment]
OS 1주차입니다!
[OS 1주차](https://principled-earthquake-2a8.notion.site/b730ae39ceab4a7aa96fcb40686261d6)

**Comment by SoobinJung1013** [comment]
[os](https://github.com/SoobinJung1013/cs-study/blob/main/OS/OperatingSystemConcept/1.md)

**Comment by yjshin229** [comment]
[OS](https://notability.com/n/10Tvy9Mjp3~AqefIKQRsf8)

동영상 재생이 안돼서 지금은 책보면서 공부하고 있습니다. 지금 시간이 너무 늦어서 일단은 챕터 1의 소규모 챕터 하나만 했고 내일 더 하게 되면 업데이트 해 놓겠습니다.

**Comment by printSANO** [comment]
[OS](https://docs.google.com/document/d/1ak-XfOUZVEYAJ26_l4ubv55U4TIE7RczOp_LaK0C9eM/edit?usp=sharing)

**Comment by h01010** [comment]
1주차 운영체제 스터디
1-1 : https://hololo-kumo.tistory.com/194
1-2 : https://hololo-kumo.tistory.com/195

**Comment by hyeontack5** [comment]
1주차 운영체제
[OS](https://hyeontack5.github.io/os/OS-%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C-%EA%B0%9C%EC%9A%94/)

**Comment by EunjiShin** [comment]
운영체제 1주차

https://velog.io/@ej_shin/1%EC%A3%BC%EC%B0%A8-%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C-%EA%B0%9C%EC%9A%94

**Comment by ksy990628** [comment]
https://velog.io/@ksy990628/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C-1%EC%A3%BC%EC%B0%A8-%EA%B3%B5%EB%B6%80

**Comment by vikira** [comment]
[os 1주차](https://dev-sailor.tistory.com/44)

**Comment by Yong-ga-ri** [comment]
https://www.notion.so/OS-88c56b09b8924e51ae9f4a2d088971b1
