### ISSUE TITLE
DB 4주차 : 데이터베이스의 운영비용, 조건 조합, 패턴 매칭 검색

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#10]
### **목표**
> 데이터베이스의 운영 비용, 검색 조건 조합, 패턴 매칭 검색 

**데이터베이스 첫걸음**
- 데이터베이스의 운영 비용

**SQL 첫걸음**
- 검색 조건 조합
- 패턴 매칭 검색 

### **마감 일시 (한국 시간 기준)**
> 2021년 10월 3일 자정

**Comment by rlathal009** [comment]
[데베](https://somsoming9.tistory.com/45)
[SQL](https://somsoming9.tistory.com/46)

**Comment by EunjiShin** [comment]
DB 4주차

[데베첫](https://velog.io/@ej_shin/3%EC%9E%A5-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4%EC%9D%98-%EC%B4%88%EA%B8%B0-%EB%B9%84%EC%9A%A9-%EC%9A%B4%EC%98%81-%EB%B9%84%EC%9A%A9)
[SQL-1](https://velog.io/@ej_shin/7%EC%9E%A5-%EC%A1%B0%EA%B1%B4-%EC%A1%B0%ED%95%A9%ED%95%98%EA%B8%B0)
[SQL-2](https://velog.io/@ej_shin/8%EC%9E%A5-%ED%8C%A8%ED%84%B4-%EB%A7%A4%EC%B9%AD%EC%97%90-%EC%9D%98%ED%95%9C-%EA%B2%80%EC%83%89)

**Comment by Gnu-Kenny** [comment]
[DB](https://github.com/Gnu-Kenny/CS-study/blob/main/Database/Chapter3_Cost/README.md)
[SQL](https://github.com/Gnu-Kenny/CS-study/tree/main/SQL/Chapter2_SELECT)

**Comment by hyeontack5** [comment]
4주차 데이터베이스
[데이터베이스_ch4](https://hyeontack5.github.io/db/DB-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4%EC%97%90-%EC%96%BD%ED%9E%8C-%EB%8F%88-%EC%9D%B4%EC%95%BC%EA%B8%B0/)
[SQL_ch4](https://hyeontack5.github.io/db/DB-%ED%85%8C%EC%9D%B4%EB%B8%94%EC%97%90%EC%84%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B2%80%EC%83%89/)

**Comment by POL6463** [comment]
[DB](https://pol6463.github.io/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4(4%EC%A3%BC%EC%B0%A8)/)

**Comment by printSANO** [comment]
[DB](https://docs.google.com/document/d/1p1Zw9jK8FWDQ8zqu4RqbHWUViwGd34An9Z2bHCdrwVk/edit?usp=sharing)

**Comment by JerryK026** [comment]
[DB](https://principled-earthquake-2a8.notion.site/3-33c50c786474440fa34049da2465e856)
[SQL](https://principled-earthquake-2a8.notion.site/7-8-292af38e32d449e6b573bc034b23ef31)

**Comment by h01010** [comment]
데이터베이스 4주차
- 데베 첫걸음 : https://hololo-kumo.tistory.com/220
- SQL 첫걸음 : https://hololo-kumo.tistory.com/221

**Comment by ksy990628** [comment]
저번주 3주차 : https://velog.io/@ksy990628/데이터베이스-SQL-첫걸음-3주차-공부
데이터베이스 4주차 : https://velog.io/@ksy990628/데이터베이스-SQL-첫걸음-4주차-공부

**Comment by Yong-ga-ri** [comment]
데이터베이스 첫걸음: https://www.notion.so/a9771c146c204f818f45ffd50e6413f4
SQL 첫걸음: https://www.notion.so/SQL-18bed26803d04a60a9e36120f121e966

**Comment by Yong-ga-ri** [comment]
데이터베이스 첫걸음: https://www.notion.so/3-d3461e70b63d4e16a4c044fa30ef046d
SQL 첫걸음: https://www.notion.so/2-4a039d8471fd4b5e9efc58c058509b2f
