### ISSUE TITLE
네트워크 4주차 : 데이터 링크 계층, HTTP 상태 코드

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#11]
### **목표**
> HTTP 상태 코드 이해, 데이터 링크 계층 이해 

**모두의 네트워크**
- 데이터 링크 계층

**그림으로 배우는 HTTP & Network**
- HTTP 상태 코드

### **마감 일시 (한국 시간 기준)**
> 2021년 10월 3일 자정

**Comment by POL6463** [comment]
[그림](https://pol6463.github.io/%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C%EB%B0%B0%EC%9A%B0%EB%8A%94(4%EC%A3%BC%EC%B0%A8)/)
[모두의 네트워크](https://pol6463.github.io/%EB%AA%A8%EB%91%90%EC%9D%98%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC(4%EC%A3%BC%EC%B0%A8)/)

**Comment by yjshin229** [comment]
[모두의 네트워크 4장 ](https://notability.com/n/DXxEApkSCkvptCnF7mGTY)
배송 현황 확인했는데 아직도 한국-미국이라고 뜨네요.. 업데이트 되는대로 알려드릴게요

**Comment by rlathal009** [comment]
[모네](https://somsoming9.tistory.com/47)
[http](https://somsoming9.tistory.com/49)

**Comment by Yong-ga-ri** [comment]
네트워크 4주차
모두의 네트워크: https://www.notion.so/4-b170bf5990b04ea8a14cf933f5427c4f
그림HN 주제: https://www.notion.so/4-HTTP-f1f5c5166d5f4cd3894104068d0067d0

**Comment by ww8007** [comment]
[모네](https://github.com/ww8007/TIL/blob/main/CS%EC%A7%80%EC%8B%9D/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC/%EB%AA%A8%EB%91%90%EC%9D%98_%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC/README.md)
[그림](https://github.com/ww8007/TIL/blob/main/CS%EC%A7%80%EC%8B%9D/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC/%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EB%8A%94_Http&NetWork/README.md)

**Comment by EunjiShin** [comment]
네트워크 4주차

[모네](https://velog.io/@ej_shin/4%EC%9E%A5-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EB%A7%81%ED%81%AC-%EA%B3%84%EC%B8%B5-%EB%9E%9C%EC%97%90%EC%84%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%A0%84%EC%86%A1%ED%95%98%EA%B8%B0)
[그림](https://velog.io/@ej_shin/4%EC%9E%A5-HTTP-%EC%83%81%ED%83%9C-%EC%BD%94%EB%93%9C)

**Comment by maengsuyeon** [comment]
네트워크 스터디 4주차
https://enchanted-parsnip-08c.notion.site/4-d69704bfece94f6a81ae347bd4c875f3

**Comment by Gnu-Kenny** [comment]
[HTTP](https://github.com/Gnu-Kenny/CS-study/blob/main/HTTP/Chapter4_Status/README.md)
[모네](https://github.com/Gnu-Kenny/CS-study/blob/main/Network/Chapter4_Data_Link/README.md)

**Comment by h01010** [comment]
4주차 네트워크
- 모네 : https://hololo-kumo.tistory.com/219
- 그림 : https://hololo-kumo.tistory.com/218

**Comment by hyeontack5** [comment]
4주차 네트워크
[모두의 네트워크_ch4](https://hyeontack5.github.io/network/Network-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EB%A7%81%ED%81%AC-%EA%B3%84%EC%B8%B5/)
[HTTP_ch4](https://hyeontack5.github.io/network/Network-%EA%B2%B0%EA%B3%BC%EB%A5%BC-%EC%A0%84%EB%8B%AC%ED%95%98%EB%8A%94-HTTP-%EC%83%81%ED%83%9C-%EC%BD%94%EB%93%9C/)

**Comment by ksy990628** [comment]
저번 3주차 네트워크 : https://velog.io/@ksy990628/모두의네트워크그림으로-배우는HTTPNetwork-3주차-공부
이번 4주차 네트워크 : https://velog.io/@ksy990628/모두의네트워크그림으로-배우는HTTPNetwork-4주차-공부

**Comment by printSANO** [comment]
[모네](https://docs.google.com/document/d/1pslpf2lGxqkA5Kq9PyrRjXGPWtsTCeO_Ho6wunGzTUM/edit?usp=sharing)

**Comment by JerryK026** [comment]
[네트워크](https://principled-earthquake-2a8.notion.site/4-a13c7ee7eaf241adaf3dec7a62e00674)
[HTTP](https://principled-earthquake-2a8.notion.site/4-HTTP-d8db13535a6941ea9bc3ceb6ba637ca3)
