### ISSUE TITLE
OS 4주차 : CPU 스케줄링

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#12]
### **목표**
> CPU 스케줄링 이해

### **마감 일시 (한국 시간 기준)**
> 2021년 10월 3일 자정

**Comment by POL6463** [comment]
OS 4주차입니다
[OS](https://pol6463.github.io/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C(4%EC%A3%BC%EC%B0%A8)/)

**Comment by printSANO** [comment]
[os](https://docs.google.com/document/d/1p6rHSMBaH4jeSguO0PW6sjjXS3syDTBafTpU-v-ApQY/edit?usp=sharing)

**Comment by ksy990628** [comment]
저번 3주차 : https://velog.io/@ksy990628/운영체제-3주차-공부
이번 4주차 :https://velog.io/@ksy990628/운영체제-4주차-공부

**Comment by hyeontack5** [comment]
4주차 운영체제
[OS_ch4](https://hyeontack5.github.io/os/OS-CPU-%EC%8A%A4%EC%BC%80%EC%A4%84%EB%A7%81/)

**Comment by JerryK026** [comment]
[OS](https://principled-earthquake-2a8.notion.site/CPU-5fd56d3df5d94dbfb5f005d343450afc)

**Comment by Yong-ga-ri** [comment]
OS: https://www.notion.so/4-d76ffd3f218a4e52b131e1b8fd641f76

**Comment by EunjiShin** [comment]
OS 4주차

[CPU](https://velog.io/@ej_shin/4%EC%A3%BC%EC%B0%A8-CPU-%EC%8A%A4%EC%BC%80%EC%A4%84%EB%A7%81)
