### ISSUE TITLE
네트워크 5주차 : 네트워크 계층, 웹 서버와 HTTP 헤더

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#13]
### **목표**
> 네트워크 계층 이해, 웹 서버와 HTTP 헤더 이해

**모두의 네트워크**
- 네트워크 계층

**그림으로 배우는 HTTP & Network**
- 웹 서버
- HTTP 헤더

### **마감 일시 (한국 시간 기준)**
> 2021년 10월 10일 자정

**Comment by Yong-ga-ri** [comment]
네트워크 5주차
모두의 네트워크: https://www.notion.so/5-4cbca8e71acd45e1a6d59104e3fd17df
그림HN 주제: https://www.notion.so/HTTP-Network-bdb0fbd7d755455db61c55dd073218bf

**Comment by POL6463** [comment]
[그림으로 배우는](https://pol6463.github.io/%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C%EB%B0%B0%EC%9A%B0%EB%8A%94(5%EC%A3%BC%EC%B0%A8)/)
[모두의 네트워크](https://pol6463.github.io/%EB%AA%A8%EB%91%90%EC%9D%98%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC(5%EC%A3%BC%EC%B0%A8)/)

**Comment by rlathal009** [comment]
[모네](https://somsoming9.tistory.com/57)
[그림](https://somsoming9.tistory.com/56)

**Comment by JerryK026** [comment]
[네트워크](https://principled-earthquake-2a8.notion.site/5-bce557fb3b60401499c2c03e2fbd63fd)
[HTTP](https://principled-earthquake-2a8.notion.site/5-HTTP-d946d02b67e4468587526594f8a71b01)

**Comment by h01010** [comment]
그림 : https://hololo-kumo.tistory.com/228
모두 : https://hololo-kumo.tistory.com/225

**Comment by Gnu-Kenny** [comment]
[모네](https://github.com/Gnu-Kenny/CS-study/blob/main/Network/Chapter5_Network_Layer/README.md
)
[그림](https://github.com/Gnu-Kenny/CS-study/blob/main/HTTP/Chapter6_HTTP_Header/README.md)

**Comment by maengsuyeon** [comment]
모네
https://enchanted-parsnip-08c.notion.site/5-3042c20e97ea406bb4dfda686123174e

**Comment by EunjiShin** [comment]
네트워크 5주차

[모네](https://velog.io/@ej_shin/5%EC%9E%A5-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC-%EA%B3%84%EC%B8%B5)
[그림1](https://velog.io/@ej_shin/5%EC%9E%A5-HTTP%EC%99%80-%EC%97%B0%EA%B3%84%ED%95%98%EB%8A%94-%EC%9B%B9-%EC%84%9C%EB%B2%84)
[그림2](https://velog.io/@ej_shin/6%EC%9E%A5-HTTP-%ED%97%A4%EB%8D%94-1)

**Comment by hyeontack5** [comment]
5주차 네트워크
[모두의 네트워크_ch5](https://hyeontack5.github.io/network/Network-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC-%EA%B3%84%EC%B8%B5/)
[HTTP_ch5](https://hyeontack5.github.io/network/Network-HTTP%EC%99%80-%EC%97%B0%EA%B3%84%ED%95%98%EB%8A%94-%EC%9B%B9-%EC%84%9C%EB%B2%84/)
