### ISSUE TITLE
OS 5주차 : 병행 제어 (1)

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#15]
### **목표**
> 병행 제어 이해

### **마감 일시 (한국 시간 기준)**
> 2021년 10월 10일 자정

**Comment by POL6463** [comment]
[OS](https://pol6463.github.io/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C(5%EC%A3%BC%EC%B0%A8)/)

**Comment by JerryK026** [comment]
[OS](https://principled-earthquake-2a8.notion.site/669893f7a15f49ac9d1a5687332e0b7d)

**Comment by ksy990628** [comment]
https://velog.io/@ksy990628/운영체제-5주차-공부

**Comment by EunjiShin** [comment]
OS 5주차

[병행제어](https://velog.io/@ej_shin/5%EC%A3%BC%EC%B0%A8-%EB%B3%91%ED%96%89-%EC%A0%9C%EC%96%B4-1)
