### ISSUE TITLE
네트워크 6주차 : 전송계층, HTTP 헤더 필드 (1)

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#16]
### **목표**
> 전송 계층 이해, HTTP/1.1 일반 헤더 필드와 리퀘스트 헤더 필드 이해

**모두의 네트워크**
- 전송 계층 

**그림으로 배우는 HTTP & Network**
- 일반 헤더 필드
- 리퀘스트 헤더 필드

### **마감 일시 (한국 시간 기준)**
> 2021년 10월 17일 자정

**Comment by POL6463** [comment]
[모네](https://pol6463.github.io/%EB%AA%A8%EB%91%90%EC%9D%98%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC(6%EC%A3%BC%EC%B0%A8)/)
[그림으로 배우는](https://pol6463.github.io/%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C%EB%B0%B0%EC%9A%B0%EB%8A%94(6%EC%A3%BC%EC%B0%A8)/)

**Comment by ww8007** [comment]
[모네](https://github.com/ww8007/TIL/blob/main/CS%EC%A7%80%EC%8B%9D/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC/%EB%AA%A8%EB%91%90%EC%9D%98_%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC/README.md)
[그림](https://github.com/ww8007/TIL/blob/main/CS%EC%A7%80%EC%8B%9D/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC/%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EB%8A%94_Http%26NetWork/ch06_HTTP_%ED%97%A4%EB%8D%94/README.md)

**Comment by JerryK026** [comment]
[네트워크](https://principled-earthquake-2a8.notion.site/6-a130046196884ba8be49d98be3d69091)
[HTTP](https://principled-earthquake-2a8.notion.site/6-HTTP-06fac1d8519d45cbad630e55881c16a7)

**Comment by hyeontack5** [comment]
6주차 네트워크
[모두의 네트워크_ch6](https://hyeontack5.github.io/network/Network-%EC%A0%84%EC%86%A1-%EA%B3%84%EC%B8%B5/)
[HTTP_ch6](https://hyeontack5.github.io/network/Network-HTTP-%ED%97%A4%EB%8D%94/)

**Comment by aeong98** [comment]
김서연 제출.
https://whispering-nylon-83d.notion.site/77d1e37c246440369c7cf22657723ebd

**Comment by ksy990628** [comment]
https://velog.io/@ksy990628/모두의네트워크그림으로-배우는HTTPNetwork-6주차-공부

**Comment by maengsuyeon** [comment]
https://enchanted-parsnip-08c.notion.site/6-5cde857409234c89b56d2e72114b0e34

**Comment by Gnu-Kenny** [comment]
[모네](https://github.com/Gnu-Kenny/CS-study/blob/main/Network/Chapter6_Transfer_Layer/README.md)
[HTTP](https://github.com/Gnu-Kenny/CS-study/blob/main/HTTP/Chapter6_HTTP_Header/README.md)
