### ISSUE TITLE
OS 6주차 : 병행 제어 (2)

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#17]
### **목표**
> 병행 제어 이해

### **마감 일시 (한국 시간 기준)**
> 2021년 10월 17일 자정

**Comment by JerryK026** [comment]
[OS](https://principled-earthquake-2a8.notion.site/669893f7a15f49ac9d1a5687332e0b7d)

**Comment by ksy990628** [comment]
https://velog.io/@ksy990628/운영체제-6주차-공부

**Comment by h01010** [comment]
[OS 6주차 병행 제어(2)](https://hololo-kumo.tistory.com/235)

**Comment by Gnu-Kenny** [comment]
[OS_ch6](https://github.com/Gnu-Kenny/CS-study/blob/main/OS/Chapter7_Deadlock/README.md)
