### ISSUE TITLE
DB 6주차 : DB 아키텍처와 LIMIT, 수치 연산

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#18]
### **목표**
> DB 아키텍처 이해, LIMIT와 수치 연산 이해

**데이터베이스 첫걸음**
- DB 아키텍처 이해

**SQL 첫걸음**
- LIMIT 
- 수치연산

### **마감 일시 (한국 시간 기준)**
> 2021년 10월 17일 자정

**Comment by POL6463** [comment]
[SQL](https://pol6463.github.io/SQL%EC%B2%AB%EA%B1%B8%EC%9D%8C(6%EC%A3%BC%EC%B0%A8)/)
[DB](https://pol6463.github.io/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4%EC%B2%AB%EA%B1%B8%EC%9D%8C(6%EC%A3%BC%EC%B0%A8)/)

**Comment by EunjiShin** [comment]
[데베첫](https://velog.io/@ej_shin/4%EC%9E%A5-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4%EC%99%80-%EC%95%84%ED%82%A4%ED%85%8D%EC%B2%98-%EA%B5%AC%EC%84%B1-1)
[SQL](https://velog.io/@ej_shin/11-12%EA%B0%95-LIMIT-%EC%88%98%EC%B9%98-%EC%97%B0%EC%82%B0)

**Comment by h01010** [comment]
데이터베이스 첫 걸음 : https://hololo-kumo.tistory.com/220
SQL 첫 걸음 : https://hololo-kumo.tistory.com/233

**Comment by hyeontack5** [comment]
6주차 데이터베이스
[데이터베이스_ch6](https://hyeontack5.github.io/db/DB-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4%EC%99%80-%EC%95%84%ED%82%A4%ED%85%8D%EC%B2%98-%EA%B5%AC%EC%84%B1/)
[SQL_ch6](https://hyeontack5.github.io/db/DB-%EC%A0%95%EB%A0%AC%EA%B3%BC-%EC%97%B0%EC%82%B0/)

**Comment by ksy990628** [comment]
https://velog.io/@ksy990628/데이터베이스-SQL-첫걸음-6주차-공부

**Comment by Gnu-Kenny** [comment]
[데베첫](https://github.com/Gnu-Kenny/CS-study/tree/main/Database/Chapter4_DB_Architecture)
[sql](https://github.com/Gnu-Kenny/CS-study/blob/main/SQL/Chapter3_ORDER_BY/README.md)
