### ISSUE TITLE
DB 1주차 : 데이터베이스란? 

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#2]
### **목표**

> 데이터베이스의 개념 이해하기.

**데이터베이스 첫걸음**
  - 데이터베이스의 역할
  - 기본 기능과 종류

**SQL 첫걸음**
  - 데이터베이스와 SQL
  

### **마감 일시 (한국 시간 기준)**

> 2021년 9월 12일 오후 11시

**Comment by JerryK026** [comment]
데이터베이스 1주차입니다!
데이터베이스 : https://principled-earthquake-2a8.notion.site/1-7e9e382e11434fec94e2da39ffb6fb5d
SQL : https://principled-earthquake-2a8.notion.site/1-2-b8c552b2fd50405a82fbe2ce08985151

**Comment by Gnu-Kenny** [comment]
데이터베이스 1주차 올립니다!
데이터베이스: [Chapter1_Database](https://github.com/Gnu-Kenny/CS-study/tree/main/Database)
SQL: [Chapter1_DB_SQL](https://github.com/Gnu-Kenny/CS-study/blob/main/SQL/Chapter1_DB_SQL/README.md)

**Comment by POL6463** [comment]
데이터베이스 1주차입니다!
https://pol6463.github.io/데이터베이스(1주차)/

**Comment by rlathal009** [comment]
데베 1주차입니다!
데이터베이스 : https://somsoming9.tistory.com/24
SQL : https://somsoming9.tistory.com/25

**Comment by hyeontack5** [comment]
1주차 데이터베이스
[데이터베이스_ch1](https://hyeontack5.github.io/db/DB-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4%EB%9E%80/)
[SQL_ch1](https://hyeontack5.github.io/db/DB-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4%EC%99%80-SQL/)

**Comment by h01010** [comment]
[데이터베이스 1주차]
- 데이터베이스 첫걸음 1장 : [](https://hololo-kumo.tistory.com/192)
- SQL 첫걸음 1장~2장 : [](https://hololo-kumo.tistory.com/191)

**Comment by EunjiShin** [comment]
데이터베이스 1주차 입니다

[데이터베이스 첫걸음](https://velog.io/@ej_shin/1%EC%9E%A5-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4%EB%9E%80)
[SQL 첫걸음 1강](https://velog.io/@ej_shin/1%EA%B0%95-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4%EC%99%80-SQL)
[SQL 첫걸음 2강](https://velog.io/@ej_shin/2%EA%B0%95-%EB%8B%A4%EC%96%91%ED%95%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4)

**Comment by SoobinJung1013** [comment]
[DB 첫걸음](https://github.com/SoobinJung1013/cs-study/blob/main/DB/SQL%EC%B2%AB%EA%B1%B8%EC%9D%8C/1.md)
[SQL 첫걸음](https://github.com/SoobinJung1013/cs-study/blob/main/DB/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4%EC%B2%AB%EA%B1%B8%EC%9D%8C/1.md)

**Comment by printSANO** [comment]
Database 첫걸음[](https://docs.google.com/document/d/14ywtJ9S8tqbxgjylFl40jwK0icEfd2jCgv04SM0jRww/edit?usp=sharing)
SQL 책은 아직 오는중입니다 ㅠㅠ

**Comment by yjshin229** [comment]
[데이터베이스 첫걸음 ](https://notability.com/n/2z4tQz6K8AsfCXBoIMlAXj)
^ 저도 아직 오는 중 입니다.

**Comment by ksy990628** [comment]
1주차 : https://velog.io/@ksy990628/SQL%EC%B2%AB%EA%B1%B8%EC%9D%8C-01-02%EA%B0%95-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4

**Comment by Yong-ga-ri** [comment]
데이터베이스 1주차 입니다

SQL 첫걸음: https://www.notion.so/SQL-18bed26803d04a60a9e36120f121e966
데이터베이스 첫걸음: https://www.notion.so/a9771c146c204f818f45ffd50e6413f4

**Comment by vikira** [comment]
[SQL](https://dev-sailor.tistory.com/45)
