### ISSUE TITLE
네트워크 8주차 : 네트워크 흐름, 쿠키 헤더 필드와 기타 헤더 필드

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#22]
### **목표**
> 전체 네트워크 흐름 이해, 쿠키 헤더 필드와 기타 헤더 필드

**모두의 네트워크**
- 전체 네트워크 흐름

**그림으로 배우는 HTTP & Network**
- 쿠키 헤더  필드
- 기타 헤더 필드

### **마감 일시 (한국 시간 기준)**
> 2021년 10월 31일 자정

**Comment by Yong-ga-ri** [comment]
모네: https://www.notion.so/8-38bf3ce9b8654fb6840106db7a422f55
그림: https://www.notion.so/6-HTTP-c6a7e71c5088412d86ff5ea762344dc9

**Comment by JerryK026** [comment]
[네트워크](https://principled-earthquake-2a8.notion.site/8-d8caa2bde106442487bf1be06c866fc3)
[http](https://principled-earthquake-2a8.notion.site/6-HTTP-a552d68bd2d04bb98f1138f98cf13a50)

**Comment by ww8007** [comment]
[모네](https://github.com/ww8007/TIL/blob/main/CS%EC%A7%80%EC%8B%9D/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC/%EB%AA%A8%EB%91%90%EC%9D%98_%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC/README.md)
[그림](https://github.com/ww8007/TIL/blob/main/CS%EC%A7%80%EC%8B%9D/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC/%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EB%8A%94_Http%26NetWork/ch06_HTTP_%ED%97%A4%EB%8D%94/README.md)

**Comment by rlathal009** [comment]
[모네7주차](https://somsoming9.tistory.com/68)
[모네 8주차](https://somsoming9.tistory.com/72?category=1022576)
[그림7주차](https://somsoming9.tistory.com/69?category=1022576)
[그림8주차](https://somsoming9.tistory.com/73?category=1022576)

**Comment by ksy990628** [comment]
https://velog.io/@ksy990628/모두의네트워크그림으로-배우는HTTPNetwork-8주차-공부

**Comment by aeong98** [comment]
https://whispering-nylon-83d.notion.site/77d1e37c246440369c7cf22657723ebd

**Comment by printSANO** [comment]
[그림](https://docs.google.com/document/d/1qx4J58cyldLsvbB_niWAaZoxFEm1wdj05Gf3zAgRfPo/edit?usp=sharing)
[몬](https://docs.google.com/document/d/1rXWHOQinzn8O3ckAWllZ-HemHA9r-sxLKKRW9m3xCcs/edit?usp=sharing)
