### ISSUE TITLE
DB 8주차 : SELECT (1), 데이터의 추가 / 삭제 / 갱신

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#23]
### **목표**
> SQL 기본 - SELECT (1),  데이터의 추가 / 삭제 / 갱신

**데이터베이스 첫걸음**
- SQL문의 기본 : SELECT (1)

**SQL 첫걸음**
- 데이터의 추가, 삭제, 갱신

### **마감 일시 (한국 시간 기준)**
> 2021년 10월 31일 자정

**Comment by hyeontack5** [comment]
8주차 데이터베이스
[데이터베이스_ch8
](https://hyeontack5.github.io/db/DB-SQL-%EB%AC%B8%EC%9D%98-%EA%B8%B0%EB%B3%B8/)[SQL_ch8](https://hyeontack5.github.io/db/DB-%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%9D%98-%EC%B6%94%EA%B0%80,-%EC%82%AD%EC%A0%9C,-%EA%B0%B1%EC%8B%A0/)

**Comment by rlathal009** [comment]
[데베7주차](https://somsoming9.tistory.com/70?category=1022575)
[데베8주차](https://somsoming9.tistory.com/74?category=1022575)
[SQL7주차](https://somsoming9.tistory.com/71?category=1022575)
[SQL 8주차](https://somsoming9.tistory.com/75?category=1022575)

**Comment by JerryK026** [comment]
[DB](https://principled-earthquake-2a8.notion.site/6-SQL-b35801745d6144ed91b5158ba59f25f7)
[SQL](https://principled-earthquake-2a8.notion.site/16-19-cac2a1a2e4bf45d3b6ba7dff5e582e38)

**Comment by Yong-ga-ri** [comment]
데베첫 6주차: https://www.notion.so/4-6be06afe99054b0c918a3b489992b807
데베첫 7주차: https://www.notion.so/5-DBMS-81f6efc69721427c8b254efe67aaf5fb
데베첫 8주차: https://www.notion.so/6-SQL-SELECT-056555afee4f4513bc501a3624a94533
SQL 6주차: https://www.notion.so/3-c4bcff17ae784288b24bb2ff49f99418
SQL 7주차: https://www.notion.so/3-c4bcff17ae784288b24bb2ff49f99418
SQL 8주차: https://www.notion.so/4-cad5e710e6d8432e8580040e6da6b695

**Comment by printSANO** [comment]
[sql](https://docs.google.com/document/d/1sKDX9o1aAYTkjZnQbJidKrhL_uv0a4i_ZJiis9yAG6c/edit?usp=sharing)
[db](https://docs.google.com/document/d/15o8jymcE-21Ri0TP2M1f_sZpJNl2ovkqoO1abwbYSBc/edit?usp=sharing)

**Comment by ksy990628** [comment]
https://velog.io/@ksy990628/데이터베이스-SQL-첫걸음-8주차-공부
