### ISSUE TITLE
OS 8주차 : 메모리 관리 (1)

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#24]
### **목표**
> 메모리 관리 (1)

### **마감 일시 (한국 시간 기준)**
> 2021년 10월 31일 자정

**Comment by POL6463** [comment]
[OS7주차](https://pol6463.github.io/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C(7%EC%A3%BC%EC%B0%A8)/)
[OS8주차](https://pol6463.github.io/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C(8%EC%A3%BC%EC%B0%A8)/)

**Comment by Yong-ga-ri** [comment]
OS 8주차: https://www.notion.so/7-5d71413b1ed24909a2fbd97fc63d74cb

**Comment by printSANO** [comment]
[os](https://docs.google.com/document/d/13qw2aA4qFwI2_KD-C98tPwS3FSTJsgaE4_wD9C9j8d4/edit?usp=sharing)

**Comment by ksy990628** [comment]
https://velog.io/@ksy990628/운영체제-8주차-공부
