### ISSUE TITLE
네트워크 9주차 : 무선 랜 통신, HTTPS

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#25]
### **목표**
> 무선 랜 통신 이해, HTTPS 이해

**모두의 네트워크**
- 무선 랜 통신

**그림으로 배우는 HTTP Network**
- HTTPS

### **마감 일시 (한국 시간 기준)**
> 2021년 11월 7일 자정

**Comment by rlathal009** [comment]
[모네](https://somsoming9.tistory.com/76)
[그림](https://somsoming9.tistory.com/77)

**Comment by POL6463** [comment]
[모네](https://pol6463.github.io/%EB%AA%A8%EB%91%90%EC%9D%98%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC(9%EC%A3%BC%EC%B0%A8)/)
[그림](https://pol6463.github.io/%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C%EB%B0%B0%EC%9A%B0%EB%8A%94(9%EC%A3%BC%EC%B0%A8)/)

**Comment by Gnu-Kenny** [comment]
[모네](https://github.com/Gnu-Kenny/CS-study/blob/main/Network/Chapter9_Wireless_LAN/README.md)
[그림](https://github.com/Gnu-Kenny/CS-study/blob/main/HTTP/Chapter7_HTTPS/README.md)

**Comment by ksy990628** [comment]
https://velog.io/@ksy990628/모두의네트워크그림으로-배우는HTTPNetwork-9주차-공부

**Comment by Yong-ga-ri** [comment]
모네: https://www.notion.so/9-34a6d42da43641b8852001a51180927c
그림: https://www.notion.so/7-HTTPS-9db2768a817a45838081cc1105012020

**Comment by EunjiShin** [comment]
8주차 : [모네](https://velog.io/@ej_shin/8%EC%9E%A5-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC-%EC%A0%84%EC%B2%B4-%ED%9D%90%EB%A6%84), [그림](https://velog.io/@ej_shin/6%EC%9E%A5-HTTP-%ED%97%A4%EB%8D%94-1)
9주차 : [모네](https://velog.io/@ej_shin/9%EC%9E%A5-%EB%AC%B4%EC%84%A0-%EB%9E%9C), [그림](https://velog.io/@ej_shin/7%EC%9E%A5-HTTPS)

**Comment by JerryK026** [comment]
[네트워크](https://principled-earthquake-2a8.notion.site/9-73894fe74ce14b49bd64b2e6906cbac7)
[HTTP](https://principled-earthquake-2a8.notion.site/HTTP-Network-da6daffefbbb44e8b718bfbe9375b897)

**Comment by msuyun1010** [comment]
8주차 : https://enchanted-parsnip-08c.notion.site/8-ce4e04bf39ec41718df0c105299bd6e9
9주차 : https://enchanted-parsnip-08c.notion.site/9-41dd02a6dddd4308aa86e093cfb6c3d6

**Comment by ww8007** [comment]
[모네](https://github.com/ww8007/TIL/blob/main/CS%EC%A7%80%EC%8B%9D/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC/%EB%AA%A8%EB%91%90%EC%9D%98_%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC/README.md)
