### ISSUE TITLE
DB 9주차 : SELECT(2), 집계와 그룹화

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#27]
### **목표**
> SQL 기본 - SELECT (2), 집계와 그룹화

**데이터베이스 첫걸음**
- SQL문의 기본 : SELECT (2)

**SQL 첫걸음**
- 집계, 그룹화

### **마감 일시 (한국 시간 기준)**
> 2021년 11월 7일 자정

**Comment by rlathal009** [comment]
[데베](https://somsoming9.tistory.com/81)
[SQL](https://somsoming9.tistory.com/82)

**Comment by POL6463** [comment]
[데이터베이스](https://pol6463.github.io/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4%EC%B2%AB%EA%B1%B8%EC%9D%8C(9%EC%A3%BC%EC%B0%A8)/)
[SQL](https://pol6463.github.io/SQL%EC%B2%AB%EA%B1%B8%EC%9D%8C(9%EC%A3%BC%EC%B0%A8)/)

**Comment by Gnu-Kenny** [comment]
[데베](https://github.com/Gnu-Kenny/CS-study/tree/main/Database/Chapter6_SQL_Basic)
[SQL](https://github.com/Gnu-Kenny/CS-study/blob/main/SQL/Chapter5_Total_Subquery/README.md)

**Comment by ksy990628** [comment]
8주차 : https://velog.io/@ksy990628/데이터베이스-SQL-첫걸음-8주차-공부
9주차 : https://velog.io/@ksy990628/데이터베이스-SQL-첫걸음-9주차-공부

**Comment by EunjiShin** [comment]
8주차 : [SQL](https://velog.io/@ej_shin/16-17-18-19%EA%B0%95-%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%9D%98-%EC%B6%94%EA%B0%80-%EC%82%AD%EC%A0%9C-%EA%B0%B1%EC%8B%A0), [데베첫](https://velog.io/@ej_shin/6-7%EC%9E%A5-SELECT)
9주차 : [SQL](https://velog.io/@ej_shin/20-21-22%EA%B0%95-%EC%A7%91%EA%B3%84-%EA%B7%B8%EB%A3%B9%ED%99%94), [데베첫](https://velog.io/@ej_shin/6-7%EC%9E%A5-SELECT)

**Comment by Yong-ga-ri** [comment]
데베첫: https://www.notion.so/6-SQL-SELECT-056555afee4f4513bc501a3624a94533
SQL: https://www.notion.so/5-76b7e0cc407b4917b3c5e1cfd4d47771

**Comment by JerryK026** [comment]
[DB](https://principled-earthquake-2a8.notion.site/6-SQL-b35801745d6144ed91b5158ba59f25f7)
[SQL](https://principled-earthquake-2a8.notion.site/20-22-0dd8c4a817b246348c9d4ee2ff6ed4cc)
