### ISSUE TITLE
네트워크 10주차 : 액세스 인증

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#28]
### **목표**
> 액세스 인증 이해

**그림으로 배우는 HTTP Network**
- 액세스 인증 

### **마감 일시 (한국 시간 기준)**
> 2021년 11월 14일 자정

**Comment by ksy990628** [comment]
https://velog.io/@ksy990628/모두의네트워크그림으로-배우는HTTPNetwork-11주차-공부

**Comment by EunjiShin** [comment]
[10주차](https://velog.io/@ej_shin/8%EC%9E%A5-%EC%95%A1%EC%84%B8%EC%8A%A4-%EC%9D%B8%EC%A6%9D)

**Comment by rlathal009** [comment]
[10주차](https://somsoming9.tistory.com/84)

**Comment by POL6463** [comment]
[10주차](https://pol6463.github.io/%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C%EB%B0%B0%EC%9A%B0%EB%8A%94(10%EC%A3%BC%EC%B0%A8)/)

**Comment by Yong-ga-ri** [comment]
10주차: https://www.notion.so/8-bbc29d4fc69e49c9a093c86e5964efb5

**Comment by JerryK026** [comment]
[HTTP](https://principled-earthquake-2a8.notion.site/8-95406b65b1b34c84a146f3dbdb743b39)

**Comment by ww8007** [comment]
[그림](https://github.com/ww8007/TIL/blob/7efb3cfe3f8c6a2351a707f98391786babc3877d/CS%EC%A7%80%EC%8B%9D/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC/%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EB%8A%94_Http%26NetWork/ch08_%EB%88%84%EA%B0%80_%EC%97%91%EC%84%B8%EC%8A%A4%ED%95%98%EA%B3%A0_%EC%9E%88%EB%8A%94%EC%A7%80%EB%A5%BC_%ED%99%95%EC%9D%B8%ED%95%98%EB%8A%94_%EC%9D%B8%EC%A6%9D/README.md)

**Comment by msuyun1010** [comment]
https://enchanted-parsnip-08c.notion.site/10-3d9e7632e454469fa195cdef4da7db77

**Comment by h01010** [comment]
https://hololo-kumo.tistory.com/244
늦게 올리게 되어 정말 죄송합니다!! ㅜ😭🥲
