### ISSUE TITLE
네트워크 1주차 : 네트워크의 기본

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#3]
### **목표**

> 네트워크 기본 지식 학습하기.<br>

**모두의 네트워크** 
  - 네트워크
  - 패킷
  - 비트와 바이트
  - 랜(LAN)
  - 왠(WAN)
  - 서버
  
**그림으로 배우는 HTTP & Network**
  - 웹과 HTTP
  - TCP/IP/DNS 
  - HTTP와의 관계 
  - URL과 URI

### **마감 일시 (한국 시간 기준)**

> 2021년 9월 12일 오후 11시

**Comment by JerryK026** [comment]
1주차 네트워크 정리입니다!
모네 : https://principled-earthquake-2a8.notion.site/1-81c5cc9f160346a9a3f5bd7281863f36
HTTP : https://principled-earthquake-2a8.notion.site/1-87102c5f3c824cb1b9b01d96f8471019

**Comment by Gnu-Kenny** [comment]
네트워크 1주차 올립니다!
모두의 네트워크: [Chapter1_Network](https://github.com/Gnu-Kenny/CS-study/blob/main/Network/Chapter1_Network/README.md)
HTTP: [Chapter1_Web_Network](https://github.com/Gnu-Kenny/CS-study/blob/main/HTTP/Chapter1_Web_Network/README.md)

**Comment by POL6463** [comment]
네트워크 1주차 올립니다!
https://pol6463.github.io/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC(1%EC%A3%BC%EC%B0%A8)/

**Comment by hyeontack5** [comment]
1주차 네트워크
[모두의 네트워크](https://hyeontack5.github.io/network/Network-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC-%EC%B2%AB%EA%B1%B8%EC%9D%8C/)
[HTTP](https://hyeontack5.github.io/network/Network-%EC%9B%B9%EA%B3%BC-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC%EC%9D%98-%EA%B8%B0%EB%B3%B8%EC%97%90-%EB%8C%80%ED%95%B4-%EC%95%8C%EC%95%84%EB%B3%B4%EC%9E%90/)

**Comment by rlathal009** [comment]
네트워크 1주차입니다

[모두의 네트워크](https://somsoming9.tistory.com/28)
[HTTP](https://somsoming9.tistory.com/29)

**Comment by EunjiShin** [comment]
네트워크 1주차 입니다 

[모두의 네트워크](https://velog.io/@ej_shin/%EB%AA%A8%EB%91%90%EC%9D%98-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC-1%EC%9E%A5-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC-%EA%B8%B0%EB%B3%B8-%EC%A7%80%EC%8B%9D)
[그림으로 보는 HTTP](https://velog.io/@ej_shin/1%EC%9E%A5-%EC%9B%B9%EA%B3%BC-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC%EC%9D%98-%EA%B8%B0%EB%B3%B8)

**Comment by SoobinJung1013** [comment]
[그림](https://github.com/SoobinJung1013/cs-study/blob/main/Network/%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C%EB%B0%B0%EC%9A%B0%EB%8A%94_http_network/1.md)
[모네](https://github.com/SoobinJung1013/cs-study/blob/main/Network/%EB%AA%A8%EB%91%90%EC%9D%98%20%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC/1.md)

**Comment by printSANO** [comment]
[모두의 네트워크](https://docs.google.com/document/d/1OPrJTuxHfxSzR85l5XFBjHx41bNv4r3p2ah5wocKVBY/edit?usp=sharing)
그림으로 보는 네트워크는 아직 책이 없습니다 ㅠㅠ

**Comment by yjshin229** [comment]
[모두의 네트워크 1장](https://notability.com/n/2l5CAvXPd31AwtkjInJ6ou)
그림으로 보는 네트워크 아직 도착 전 입니다.

**Comment by ksy990628** [comment]
https://velog.io/@ksy990628/%EB%AA%A8%EB%91%90%EC%9D%98%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C-%EB%B0%B0%EC%9A%B0%EB%8A%94HTTPNetwork

**Comment by Yong-ga-ri** [comment]
1주차 네트워크 공부내용입니다
.
그림으로 배우는 HTTP & Network: https://www.notion.so/HTTP-Network-bdb0fbd7d755455db61c55dd073218bf
모두의 네트워크: https://www.notion.so/7bc6e6a184d54be7b6916e925e4d94d4

**Comment by h01010** [comment]
네트워크 1주차
모두의 네트워크 : https://hololo-kumo.tistory.com/196
그림 http&network : https://hololo-kumo.tistory.com/193?category=0

**Comment by aeong98** [comment]
네트워크 스터디 노션입니다.
https://whispering-nylon-83d.notion.site/77d1e37c246440369c7cf22657723ebd

**Comment by maengsuyeon** [comment]
네트워크 1주차 스터디❕
https://enchanted-parsnip-08c.notion.site/1-71cdb0a3bc6c497a9149409640bd5796

**Comment by vikira** [comment]
[모두의 네트워크](https://vikira.github.io/Network-%EB%AA%A8%EB%91%90%EC%9D%98-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC-%EC%B1%85-1%EC%9E%A5/)

[그림으로 보는 http ](https://vikira.github.io/Network-HTTP-network-basic-1%EC%9E%A5/)
