### ISSUE TITLE
DB 10주차 : 트랜잭션과 동시성 제어, 서브쿼리

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#30]
### **목표**
> 트랜잭션과 동시성 제어 이해
> 서브쿼리와 상관 서브쿼리 이해

**데이터베이스 첫걸음**
- 트랜잭션과 동시성 제어

**SQL 첫걸음**
- 서브쿼리와 상관 서브쿼리 

### **마감 일시 (한국 시간 기준)**
> 2021년 11월 14일 자정

**Comment by rlathal009** [comment]
[데베](https://somsoming9.tistory.com/87)
[SQL](https://somsoming9.tistory.com/89)

**Comment by ksy990628** [comment]
https://velog.io/@ksy990628/데이터베이스-SQL-첫걸음-10주차-공부

**Comment by EunjiShin** [comment]
[데베첫](https://velog.io/@ej_shin/7%EC%9E%A5-%ED%8A%B8%EB%9E%9C%EC%9E%AD%EC%85%98%EA%B3%BC-%EB%8F%99%EC%8B%9C%EC%84%B1-%EC%A0%9C%EC%96%B4)
[SQL](https://velog.io/@ej_shin/23-24%EA%B0%95-%EC%84%9C%EB%B8%8C%EC%BF%BC%EB%A6%AC-%EC%83%81%EA%B4%80-%EC%84%9C%EB%B8%8C%EC%BF%BC%EB%A6%AC)

**Comment by POL6463** [comment]
[데베](https://pol6463.github.io/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4%EC%B2%AB%EA%B1%B8%EC%9D%8C(10%EC%A3%BC%EC%B0%A8)/)
[SQL](https://pol6463.github.io/SQL%EC%B2%AB%EA%B1%B8%EC%9D%8C(10%EC%A3%BC%EC%B0%A80/)

**Comment by JerryK026** [comment]
[DB](https://principled-earthquake-2a8.notion.site/7-bebacce8968a43408a2b9669248d177a)
[SQL](https://principled-earthquake-2a8.notion.site/23-24-55c6199341344b46bee4e9224810fa86)
