### ISSUE TITLE
DB 11주차 : 테이블 설계, DB객체, 테이블 작성과 제약

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#31]
### **목표**
> 테이블 설계 이해
> DB 객체, 테이블 작성과 작성 제약

**데이터베이스 첫걸음**
- 테이블 설계 이해

**SQL 첫걸음**
- DB 객체 이해
- 테이블 작성/삭제/변경
- 테이블 작성 제약

### **마감 일시 (한국 시간 기준)**
> 2021년 11월 28일 자정

**Comment by POL6463** [comment]
[데이터베이스](https://pol6463.github.io/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4(11%EC%A3%BC%EC%B0%A8)/)

**Comment by rlathal009** [comment]
[데베](https://somsoming9.tistory.com/96)
[SQL](https://somsoming9.tistory.com/97)

**Comment by JerryK026** [comment]
[DB](https://principled-earthquake-2a8.notion.site/8-a3098bb9c7404071851d4866d455d2fb)
[SQL](https://principled-earthquake-2a8.notion.site/25-27-a81b9cfda9ce454ea9324cddac0d7f6d)

**Comment by ksy990628** [comment]
https://velog.io/@ksy990628/데이터베이스-SQL-첫걸음-11주차-공부

**Comment by h01010** [comment]
데이터베이스 첫걸음 : https://hololo-kumo.tistory.com/241
SQL 첫걸음 : https://hololo-kumo.tistory.com/242

**Comment by Yong-ga-ri** [comment]
10주차
  데베첫: https://zigzag-cadet-126.notion.site/7-ad278265a1d24f0f9b97e1598f095807
  SQL첫: https://zigzag-cadet-126.notion.site/5-76b7e0cc407b4917b3c5e1cfd4d47771
11주차
  데베첫: https://zigzag-cadet-126.notion.site/8-f3cdc2236e28402eb7a1b98de751bbf9
  SQL첫: https://zigzag-cadet-126.notion.site/6-e9d5bc87504a4108a3a270eb49b7ef96
