### ISSUE TITLE
OS 11주차 : 파일 시스템 (1)

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#32]
### **목표**
> 파일 시스템 이해

### **마감 일시 (한국 시간 기준)**
> 2021년 11월 28일 자정

**Comment by Yong-ga-ri** [comment]
OS 11주차: https://www.notion.so/11-2a83a7c39e51482b86e22765aec4b1af

**Comment by JerryK026** [comment]
[OS](https://principled-earthquake-2a8.notion.site/77c957a8460643df8df4868860b06d89)

**Comment by POL6463** [comment]
[OS](https://pol6463.github.io/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C(11%EC%A3%BC%EC%B0%A8)/)
