### ISSUE TITLE
네트워크 11주차 : HTTP에 기능을 추가한 프로토콜

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#33]
### **목표**
> HTTP에 기능을 추가한 프로토콜

**그림으로 배우는 HTTP Network**
- HTTP에 기능을 추가한 프로토콜

### **마감 일시 (한국 시간 기준)**
> 2021년 11월 28일 자정

**Comment by POL6463** [comment]
[네트워크](https://pol6463.github.io/%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C%EB%B0%B0%EC%9A%B0%EB%8A%94(11%EC%A3%BC%EC%B0%A8)/)

**Comment by Yong-ga-ri** [comment]
11주차 네트워크: https://www.notion.so/9-HTTP-9581691d3eb9484494a6e32bd50364c1

**Comment by rlathal009** [comment]
[네트워크](https://somsoming9.tistory.com/95)

**Comment by JerryK026** [comment]
[네트워크](https://principled-earthquake-2a8.notion.site/9-HTTP-f60e747b6aa34580a60a96730e8f8b4b)

**Comment by msuyun1010** [comment]
https://enchanted-parsnip-08c.notion.site/11-e45b5b60d9994d1cb67001d1aad7ff2c

**Comment by h01010** [comment]
https://hololo-kumo.tistory.com/243

늦게 올리게 되어 정말 죄송합니다😭

**Comment by ksy990628** [comment]
https://velog.io/@ksy990628/모두의네트워크그림으로-배우는HTTPNetwork-11주차-공부
