### ISSUE TITLE
네트워크 12주차 : 웹 콘텐츠에서 사용하는 기술

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#34]
### **목표**
> 웹 콘텐츠에서 사용하는 기술

**그림으로 배우는 HTTP Network**
- 웹 콘텐츠에서 사용하는 기술

### **마감 일시 (한국 시간 기준)**
> 2021년 12월 5일 자정

**Comment by Yong-ga-ri** [comment]
12주차 네트워크: https://zigzag-cadet-126.notion.site/10-f81b310e39774b868f66785908b0284d

**Comment by JerryK026** [comment]
[HTTP](https://principled-earthquake-2a8.notion.site/10-6f71725f81304281a9607d142bee4ce7)

**Comment by POL6463** [comment]
[네트워크](https://pol6463.github.io/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC(12%EC%A3%BC%EC%B9%98)/)

**Comment by rlathal009** [comment]
[HTTP](https://somsoming9.tistory.com/99)

**Comment by h01010** [comment]
https://hololo-kumo.tistory.com/246

**Comment by ksy990628** [comment]
https://velog.io/@ksy990628/모두의네트워크그림으로-배우는HTTPNetwork-12주차-공부
