### ISSUE TITLE
OS 12주차 : 파일시스템 (2)

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#35]
### **목표**
> 파일 시스템 이해 2

### **마감 일시 (한국 시간 기준)**
> 2021년 12월 5일 자정

**Comment by Yong-ga-ri** [comment]
OS 12주차: https://zigzag-cadet-126.notion.site/12-aa5b88a0ad3d436e8bd1b314ac13c8ab

**Comment by JerryK026** [comment]
[OS](https://principled-earthquake-2a8.notion.site/77c957a8460643df8df4868860b06d89)

**Comment by POL6463** [comment]
[OS](https://pol6463.github.io/%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C(12%EC%A3%BC%EC%B0%A8)/)

**Comment by h01010** [comment]
https://hololo-kumo.tistory.com/249
