### ISSUE TITLE
DB 12주차 : 테이블 설계와 인덱스, 뷰

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#36]
### **목표**
> 테이블 설계 이해 (2)
> 인덱스와 뷰 이해

**데이터베이스 첫걸음**
- 테이블 설계 이해 (2)

**SQL 첫걸음**
- 인덱스 이해
- 뷰 이해

### **마감 일시 (한국 시간 기준)**
> 2021년 12월 5일 자정

**Comment by Yong-ga-ri** [comment]
데베첫 12주차: https://zigzag-cadet-126.notion.site/8-f3cdc2236e28402eb7a1b98de751bbf9
SQL 첫 걸음 12주차: https://zigzag-cadet-126.notion.site/6-e9d5bc87504a4108a3a270eb49b7ef96

**Comment by POL6463** [comment]
[데이터베이스](https://pol6463.github.io/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4(12%EC%A3%BC%EC%B0%A8)/)

**Comment by JerryK026** [comment]
[DB}(https://principled-earthquake-2a8.notion.site/8-a3098bb9c7404071851d4866d455d2fb)

**Comment by rlathal009** [comment]
[DB](https://somsoming9.tistory.com/100)
[SQL](https://somsoming9.tistory.com/101)

**Comment by h01010** [comment]
https://hololo-kumo.tistory.com/247
https://hololo-kumo.tistory.com/248

**Comment by ksy990628** [comment]
https://velog.io/@ksy990628/데이터베이스-SQL-첫걸음-12주차-공부
