### ISSUE TITLE
DB 2주차 : RDB와 데이터 서버, Hello World

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#4]
### **목표**
> RDB와 DB서버를 이해하고 데이터 검색 해보기 

**데이터베이스 첫걸음**
- 관계형 데이터베이스

**SQL 첫걸음**
- 데이터베이스 서버
- Hello World

### **마감 일시 (한국 시간 기준)**
> 2021년 9월 19일 자정

**Comment by POL6463** [comment]
DB 2주차입니다!
https://pol6463.github.io/데이터베이스(2주차)/

**Comment by EunjiShin** [comment]
DB 2주차 입니다

[데베첫](https://velog.io/@ej_shin/2%EC%9E%A5-%EA%B4%80%EA%B3%84%ED%98%95-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4%EB%9E%80)
[SQL 3강](https://velog.io/@ej_shin/3%EA%B0%95-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4-%EC%84%9C%EB%B2%84)
[SQL 4강](https://velog.io/@ej_shin/4%EA%B0%95-Hello-World-%EC%8B%A4%ED%96%89%ED%95%98%EA%B8%B0)

**Comment by rlathal009** [comment]
2주차입니다

[데이터베이스 첫걸음](https://somsoming9.tistory.com/30)
[SQL 첫걸음](https://somsoming9.tistory.com/31)

**Comment by JerryK026** [comment]
DB 2주차입니다!

[DB](https://principled-earthquake-2a8.notion.site/2-82268572d8ed47aca6ac0b7bfdf38137)
[SQL](https://principled-earthquake-2a8.notion.site/3-4-f662878024dd4afb8298f61df2471c57)

**Comment by Yong-ga-ri** [comment]
DB: https://www.notion.so/2-00cbf3654a4c446595139e356e58ba14
SQL: https://www.notion.so/1-SQL-435d2b1a68eb493a8b2e90bc919e33a1
         https://www.notion.so/2-4a039d8471fd4b5e9efc58c058509b2f

**Comment by ksy990628** [comment]
https://velog.io/@ksy990628/데이터베이스-SQL-첫걸음-2주차-공부-fyrgwslo

**Comment by Gnu-Kenny** [comment]
데이터베이스 2주차입니다.
[데이터베이스 설계 2주차](https://github.com/Gnu-Kenny/CS-study/blob/main/Database/Chapter2_RDB/README.md)
[SQL 2주차_1](https://github.com/Gnu-Kenny/CS-study/blob/main/SQL/Chapter1_DB_SQL/README.md
)[SQL 2주차_2](https://github.com/Gnu-Kenny/CS-study/blob/main/SQL/Chapter2_SELECT/README.md)

**Comment by hyeontack5** [comment]
2주차 데이터베이스
[데이터베이스_ch2](https://hyeontack5.github.io/db/DB-%EA%B4%80%EA%B3%84%ED%98%95-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4%EB%9E%80/)
[SQL_ch2](https://hyeontack5.github.io/db/DB-%ED%85%8C%EC%9D%B4%EB%B8%94%EC%97%90%EC%84%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B2%80%EC%83%89/)

**Comment by printSANO** [comment]
[DB 2주차](https://docs.google.com/document/d/1hv61fOH2RQpQrUjFENRkTpB8G9V7rNHFnzUskijMyVs/edit?usp=sharing)

**Comment by h01010** [comment]
데이터베이스 2주차
데이터베이스 첫걸음 : https://hololo-kumo.tistory.com/204
SQL 첫걸음 : https://hololo-kumo.tistory.com/203

**Comment by yjshin229** [comment]
[데이터베이스 첫걸음 2주차](https://notability.com/n/2v_vck_SC0MvF_X3i9taAn)
sql 첫걸음 배송 전 입니다.
