### ISSUE TITLE
네트워크 2주차 : 네트워크 통신 규칙, 프로토콜 HTTP 

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#5]
### **목표**
> 네트워크 통신 규칙과 프로토콜 HTTP 이해 

**모두의 네트워크**
- 네트워크 통신 규칙

**그림으로 배우는 HTTP & Network**
- 프로토콜 HTTP 

### **마감 일시 (한국 시간 기준)**
> 2021년 9월 19일 자정

**Comment by EunjiShin** [comment]
네트워크 2주차

[모네](https://velog.io/@ej_shin/2%EC%9E%A5-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC%EC%9D%98-%EA%B8%B0%EB%B3%B8-%EA%B7%9C%EC%B9%99)
[그림HTTP](https://velog.io/@ej_shin/2%EC%9E%A5-%EA%B0%84%EB%8B%A8%ED%95%9C-%ED%94%84%EB%A1%9C%ED%86%A0%EC%BD%9C-HTTP)

**Comment by JerryK026** [comment]
네트워크 2주차입니다!

[모네](https://principled-earthquake-2a8.notion.site/2-c4540ef8673d40d3886b1484899bd659)
[HTTP](https://principled-earthquake-2a8.notion.site/2-HTTP-81c6e7b0ac4f4af6ab190c619a5d504c)

**Comment by POL6463** [comment]
네트워크 2주차입니다

[모네](https://pol6463.github.io/%EB%AA%A8%EB%91%90%EC%9D%98%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC(2%EC%A3%BC%EC%B0%A8)/)
[그림HTTP](https://pol6463.github.io/%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C%EB%B0%B0%EC%9A%B0%EB%8A%94(2%EC%A3%BC%EC%B0%A8)/)

**Comment by Yong-ga-ri** [comment]
모두의 네트워크: https://www.notion.so/2-be0d6878a9604bd6a7544e904eb6d2b1
그림HTTP: https://www.notion.so/2-HTTP-4f687ae871b245abb349c3ed526459ef

**Comment by ksy990628** [comment]
https://velog.io/@ksy990628/%EB%AA%A8%EB%91%90%EC%9D%98%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C-%EB%B0%B0%EC%9A%B0%EB%8A%94HTTPNetwork-2%EC%A3%BC%EC%B0%A8-%EA%B3%B5%EB%B6%80

**Comment by h01010** [comment]
네트워크 2주차 정리입니다.
모네 : https://hololo-kumo.tistory.com/198
그림 h&n : https://hololo-kumo.tistory.com/200

**Comment by rlathal009** [comment]
[모네](https://somsoming9.tistory.com/36)
[http](https://somsoming9.tistory.com/37)

**Comment by hyeontack5** [comment]
2주차 네트워크
[모두의 네트워크_ch2](https://hyeontack5.github.io/network/Network-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC%EC%9D%98-%EA%B8%B0%EB%B3%B8-%EA%B7%9C%EC%B9%99/)
[HTTP_ch2](https://hyeontack5.github.io/network/Network-%EA%B0%84%EB%8B%A8%ED%95%9C-%ED%94%84%EB%A1%9C%ED%86%A0%EC%BD%9C-HTTP/)

**Comment by Gnu-Kenny** [comment]
네트워크 2주차입니다.
[모두의 네트워크 2장](https://github.com/Gnu-Kenny/CS-study/blob/main/Network/Chapter2_Rule/README.md)
[HTTP 2장](https://github.com/Gnu-Kenny/CS-study/blob/main/HTTP/Chapter2_Http_Protocol/README.md)

**Comment by printSANO** [comment]
[모네 2주차](https://docs.google.com/document/d/1PSsur_YD2_2BhM_u9NvvNpy-6wqLa1a096LzFxFV8HY/edit?usp=sharing)

**Comment by maengsuyeon** [comment]
네트워크 2주차 스터디
https://enchanted-parsnip-08c.notion.site/2-a8ab408d06c24ce9a2d4e66c484d3cca

**Comment by aeong98** [comment]
네트워크 2주차 스터디 입니다.
https://whispering-nylon-83d.notion.site/77d1e37c246440369c7cf22657723ebd

**Comment by yjshin229** [comment]
[모네 2주차](https://notability.com/n/1EtS9Ywrd6DAmSZbaAJHz1)
그림으로 배우는 HTTP 아직 도착 전 입니다.

**Comment by ww8007** [comment]
네트워크 2주차 입니다.
[모두의 네트워크](https://github.com/ww8007/TIL/blob/main/CS%EC%A7%80%EC%8B%9D/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC/%EB%AA%A8%EB%91%90%EC%9D%98_%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC/README.md)
[그림으로 배우는 HTTP](https://github.com/ww8007/TIL/blob/main/CS%EC%A7%80%EC%8B%9D/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC/%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EB%8A%94_Http&NetWork/README.md)
