### ISSUE TITLE
OS 2주차 : 컴퓨터 시스템의 구조 이해 

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#6]
### **목표**
> 컴퓨터 시스템의 구조 이해하기.

### **마감 일시 (한국 시간 기준)**
> 2021년 9월 19일 자정

**Comment by JerryK026** [comment]
OS 2주차입니다!
[OS 2주차](https://principled-earthquake-2a8.notion.site/8b65db9e93aa4959990e788a3557dc84)

**Comment by POL6463** [comment]
OS 2주차입니다
[OS 2주차](https://pol6463.github.io/OS(2%EC%A3%BC%EC%B0%A8)/)

**Comment by Yong-ga-ri** [comment]
OS 2주차: https://www.notion.so/2-f4b9a2098d6f41dbbd1369249fb521f6

**Comment by EunjiShin** [comment]
OS 2주차입니다~

[2주차 : 컴퓨터 시스템 구조](https://velog.io/@ej_shin/2%EC%A3%BC%EC%B0%A8-%EC%BB%B4%ED%93%A8%ED%84%B0-%EC%8B%9C%EC%8A%A4%ED%85%9C%EC%9D%98-%EA%B5%AC%EC%A1%B0)

**Comment by hyeontack5** [comment]
2주차 운영체제
[OS_ch2](https://hyeontack5.github.io/os/OS-%EC%BB%B4%ED%93%A8%ED%84%B0%EC%8B%9C%EC%8A%A4%ED%85%9C%EC%9D%98-%EA%B5%AC%EC%A1%B0/)

**Comment by Gnu-Kenny** [comment]
운영체제 2주차 내용입니다.
[OS_Chapter2_1](https://github.com/Gnu-Kenny/CS-study/blob/main/OS/Chapter1_OS_Summary/README.md) 
[OS_Chapter2_2](https://github.com/Gnu-Kenny/CS-study/blob/main/OS/Chapter2_Computer_Architecture/README.md)

**Comment by printSANO** [comment]
[OS](https://docs.google.com/document/d/1iTl5_x5itEZdR3Uzyo89ReWSLNuG-s9ky6OJIuGgd0E/edit?usp=sharing)

**Comment by ksy990628** [comment]
https://velog.io/@ksy990628/운영체제-2주차-공부

**Comment by h01010** [comment]
2주차 운영체제
2-1~2-2 : https://hololo-kumo.tistory.com/206
2-3~2-4 : https://hololo-kumo.tistory.com/207
