### ISSUE TITLE
네트워크 3주차 : HTTP 메세지와 물리 계층

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#7]
### **목표**
> HTTP 메세지 이해, 네트워크 물리 계층 이해 

**모두의 네트워크**
- 물리 계층

**그림으로 배우는 HTTP & Network**
- HTTP 메시지

### **마감 일시 (한국 시간 기준)**
> 2021년 9월 26일 자정

**Comment by yjshin229** [comment]
[모네 3장 ](https://notability.com/n/2WushvmEW3YeQjcGnmPCfe)

**Comment by POL6463** [comment]
[모네](https://pol6463.github.io/%EB%AA%A8%EB%91%90%EC%9D%98%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC(3%EC%A3%BC%EC%B0%A8)/)
[그림으로 배우는](https://pol6463.github.io/%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C%EB%B0%B0%EC%9A%B0%EB%8A%94(3%EC%A3%BC%EC%B0%A8)/)

**Comment by JerryK026** [comment]
[네트워크](https://principled-earthquake-2a8.notion.site/3-87c76bd7690649babc06e135ee636132)
[HTTP](https://principled-earthquake-2a8.notion.site/3-HTTP-HTTP-7a858e157fe646359a0bcf09ea79b439)

**Comment by ww8007** [comment]
[모네](https://github.com/ww8007/TIL/blob/main/CS%EC%A7%80%EC%8B%9D/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC/%EB%AA%A8%EB%91%90%EC%9D%98_%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC/README.md)
[그림으로 배우는 HTTP](https://github.com/ww8007/TIL/blob/main/CS%EC%A7%80%EC%8B%9D/%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC/%EA%B7%B8%EB%A6%BC%EC%9C%BC%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EB%8A%94_Http&NetWork/README.md)

**Comment by printSANO** [comment]
[network](https://docs.google.com/document/d/16GwGgHGc6UPagEBamAAI5pnrhfslNEX5bugg1z7VLTw/edit?usp=sharing)

**Comment by hyeontack5** [comment]
3주차 네트워크
[모두의 네트워크_ch2](https://hyeontack5.github.io/network/Network-%EB%AC%BC%EB%A6%AC-%EA%B3%84%EC%B8%B5/)
[HTTP_ch3](https://hyeontack5.github.io/network/Network-HTTP-%EC%A0%95%EB%B3%B4%EB%8A%94-HTTP-%EB%A9%94%EC%86%8C%EB%93%9C%EC%97%90-%EC%9E%88%EB%8B%A4/)

**Comment by aeong98** [comment]
김서연 
3주차 네트워크
https://whispering-nylon-83d.notion.site/77d1e37c246440369c7cf22657723ebd

**Comment by rlathal009** [comment]
[모네](https://somsoming9.tistory.com/38)
[HTTP](https://somsoming9.tistory.com/39)

**Comment by h01010** [comment]
네트워크 3주차
모네 : https://hololo-kumo.tistory.com/211
그림 : https://hololo-kumo.tistory.com/214

**Comment by EunjiShin** [comment]
네트워크 3주차

[모네](https://velog.io/@ej_shin/3%EC%9E%A5-%EB%AC%BC%EB%A6%AC-%EA%B3%84%EC%B8%B5-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%A5%BC-%EC%A0%84%EA%B8%B0-%EC%8B%A0%ED%98%B8%EB%A1%9C-%EB%B3%80%ED%99%98%ED%95%98%EA%B8%B0)
[그림](https://velog.io/@ej_shin/3%EC%9E%A5-%ED%94%84%EB%A1%9C%ED%86%A0%EC%BD%9C-%EB%A9%94%EC%84%B8%EC%A7%80)

**Comment by Gnu-Kenny** [comment]
네트워크 3주차입니다.

[모네](https://github.com/Gnu-Kenny/CS-study/blob/main/Network/Chapter3_Physical_Layer/README.md)
[HTTP](https://github.com/Gnu-Kenny/CS-study/tree/main/HTTP/Chapter3_Http_Message)

**Comment by Yong-ga-ri** [comment]
네트워크 3주차
모두의 네트워크: https://www.notion.so/3-f6e9f690e8004663b96f687f85bfb59b
그림HN 주제: https://www.notion.so/3-HTTP-HTTP-75fa45db9d4846e787514aec29253578

**Comment by maengsuyeon** [comment]
네트워크 3주차
https://enchanted-parsnip-08c.notion.site/3-fbccce15fd1c413f9ffcbec9e902dc35

**Comment by ksy990628** [comment]
저번에 사유가 있어서 올리지 못한 3주차 네트워크입니다!
https://velog.io/@ksy990628/모두의네트워크그림으로-배우는HTTPNetwork-3주차-공부
