### ISSUE TITLE
DB 3주차 : 데이터베이스의 비용과 참조, 검색 조건

### ISSUE THREAD

**Issue by EunjiShin** [EunjiShin/CS-study#9]
### **목표**
> 데이터베이스의 초기/운영 비용, 테이블 구조 참조와 검색 조건 

**데이터베이스 첫걸음**
- 데이터베이스의 초기 비용

**SQL 첫걸음**
- 테이블 구조 참조
- 검색 조건 지정

### **마감 일시 (한국 시간 기준)**
> 2021년 9월 26일 자정

**Comment by JerryK026** [comment]
[데이터베이스](https://principled-earthquake-2a8.notion.site/3-33c50c786474440fa34049da2465e856)
[SQL](https://principled-earthquake-2a8.notion.site/5-6-6d7e37000c2146339f3a66297d0373f3)

**Comment by POL6463** [comment]
[데이터베이스](https://pol6463.github.io/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4(3%EC%A3%BC%EC%B0%A8)/)

**Comment by printSANO** [comment]
[DB](https://docs.google.com/document/d/1J49U-G8miaF7AGyCMRfwXnaa_Ll81VWkm14rwb2yRQA/edit?usp=sharing)

**Comment by rlathal009** [comment]
[데이터베이스](https://somsoming9.tistory.com/40?category=1022575)
[SQL](https://somsoming9.tistory.com/41?category=1022575)

**Comment by hyeontack5** [comment]
3주차 데이터베이스
[데이터베이스_ch3
](https://hyeontack5.github.io/db/DB-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4%EC%97%90-%EC%96%BD%ED%9E%8C-%EB%8F%88-%EC%9D%B4%EC%95%BC%EA%B8%B0/)[SQL_ch3](https://hyeontack5.github.io/db/DB-%ED%85%8C%EC%9D%B4%EB%B8%94%EC%97%90%EC%84%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B2%80%EC%83%89/)

**Comment by EunjiShin** [comment]
데이터베이스 3주차

[SQL_5강](https://velog.io/@ej_shin/5%EA%B0%95-%ED%85%8C%EC%9D%B4%EB%B8%94-%EA%B5%AC%EC%A1%B0-%EC%B0%B8%EC%A1%B0%ED%95%98%EA%B8%B0)
[SQL_6강](https://velog.io/@ej_shin/6%EA%B0%95-%EA%B2%80%EC%83%89-%EC%A1%B0%EA%B1%B4-%EC%A7%80%EC%A0%95%ED%95%98%EA%B8%B0)
[데베첫
](https://velog.io/@ej_shin/3%EC%9E%A5-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4%EC%9D%98-%EC%B4%88%EA%B8%B0-%EB%B9%84%EC%9A%A9-%EC%9A%B4%EC%98%81-%EB%B9%84%EC%9A%A9)

**Comment by h01010** [comment]
데이터베이스 3주차
db 첫걸음 : https://hololo-kumo.tistory.com/216
SQL 첫걸음 : https://hololo-kumo.tistory.com/215

**Comment by Gnu-Kenny** [comment]
데이터베이스 3주차 입니다.
[DB 첫걸음 3장](https://github.com/Gnu-Kenny/CS-study/tree/main/Database/Chapter3_Cost)
[SQL 2장_5장, 6장](https://github.com/Gnu-Kenny/CS-study/tree/main/SQL/Chapter2_SELECT)

**Comment by Yong-ga-ri** [comment]
데이터베이스 첫걸음: https://www.notion.so/3-d3461e70b63d4e16a4c044fa30ef046d
SQL 첫걸음: https://www.notion.so/2-4a039d8471fd4b5e9efc58c058509b2f

**Comment by ksy990628** [comment]
저번 3주차입니다 : https://velog.io/@ksy990628/데이터베이스-SQL-첫걸음-3주차-공부
